name: "License-Preprocessing"
backend: "python"
max_batch_size: 64

input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [3, 1080, 1920]
  }
]

output [
  {
    name: "input_image"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]

dynamic_batching {
  preferred_batch_size: [8, 16, 32]
  max_queue_delay_microseconds: 50
  preserve_ordering: false
}