name: "Trocr-Pre"
backend: "python"
max_batch_size: 0  
input [
    {
        name: "image"
        data_type: TYPE_FP32
        dims: [-1,3,1080,1920]
    },
    {
        name: "det_bboxes"
        data_type: TYPE_FP32
        dims: [ -1, 4 ]
    }
]

output[
    {
        name: "cropped_plates"
        data_type: TYPE_FP32
        dims:[-1,3,200,400]
    }
]
