name: "License-Detection-Postprocessing"
backend: "python"
max_batch_size: 0  

input [
  {
    name: "output1"
    data_type: TYPE_FP32
    dims: [ -1, 5, 8400 ]  
  }
]

output [
  {
    name: "num_detections"
    data_type: TYPE_INT32
    dims: [ -1 ]  # [batch_size] - number of detections per image
  },
  {
    name: "det_bboxes"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]  # [total_boxes, 4] - all boxes across batch
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ -1 ]  # [total_boxes] - flattened scores
  },
  {
    name: "bbox_batch_index"
    data_type: TYPE_INT32
    dims: [ -1 ]  # [total_boxes] - tells which image each box belongs to
  }
]